# Generated by Django 4.1.2 on 2022-10-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_file_upload_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_file_upload',
            fields=[
                ('idsd', models.AutoField(primary_key=True, serialize=False)),
                ('file_named', models.CharField(max_length=255)),
                ('timestampd', models.DateTimeField(auto_now_add=True)),
                ('my_filed', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='file_upload',
            new_name='video_audio_file_upload',
        ),
    ]
