# Generated by Django 4.1.2 on 2022-10-23 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_document_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_audio_file_upload',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
