# Generated by Django 4.1.2 on 2022-10-23 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_video_audio_file_upload_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_audio_file_upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 7, 36, 23, 86787, tzinfo=datetime.timezone.utc)),
        ),
    ]
