# Generated by Django 4.1.2 on 2022-10-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_video_audio_file_upload_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_audio_file_upload',
            name='file_path',
        ),
    ]
